openapi: 3.0.3
info:
  title: API portal - OpenAPI 3.0
  description: |-
    This is a backend to manage api proxies
  contact:
    email: mallik.partha@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:9001
tags:
  - name: subdomains
    description: All functionalities for managing subdomains
  - name: gateways
    description: All functionalities for managing gateways
paths:
  /apis/v1/subdomains:
    get:
      tags:
        - subdomains
      summary: Get all subdomains
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subdomain-Get' 
    post:
      tags:
        - subdomains
      summary: Create a Subdomain
      requestBody:
        description: The body to create Subdomain
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subdomain-Create'
            example:
                name: 'xyz.com'
      responses:
        '500':
          description: Internal Server error
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subdomain-Get' 

  /apis/v1/subdomains/{subdomain_id}:
    get:
      tags:
        - subdomains
      summary: Get subdomain by Id
      parameters:
        - name: subdomain_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subdomain-Get'
  /apis/v1/subdomains/{subdomain_id}/gateways/{gateway_id}:
    get:
      tags:
        - gateways
      summary: Get subdomain by Id
      parameters:
        - name: subdomain_id
          in: path
          required: true
          schema:
            type: string
        - name: gateway_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subdomain-Get'
  /apis/v1/subdomains/{subdomain_id}/gateways:
    get:
      tags:
        - gateways
      summary: Get subdomain by Id
      parameters:
        - name: subdomain_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gateway-Get'
    post:
      tags:
        - gateways
      summary: Create a Gatweay
      parameters:
        - name: subdomain_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: The body to create Gateway
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gateway-Create'
            example:
                name: 'Kong'
                url: 'http://kong.abc.com/proxy'
                subdomain_id: 1
      responses:
        '404':
          description: Subdomain Id not found
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gateway-Get' 
components:
  schemas:
    Subdomain-Create:
      type: object
      properties:
        name:
          type: string
          example: 'abc.com'
    Subdomain-Get:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 'abc.com'
        createdby:
          type: string
          example: 'partha'
        modifiedby:
          type: string
          example: 'partha'
        createdat:
          type: string
          format: date-time
          example: '2022-12-06T15:47:56.010Z'
        modifiedat:
          type: string
          format: date-time
          example: '2022-12-06T15:47:56.010Z'
    Gateway-Create:
      type: object
      properties:
        name:
          type: string
          example: 'Kong'
        url:
          type: string
          example: 'http://kong.abc.com/proxy'
        subdomain_id:
          type: integer
          format: int64
          example: 10
          
    Gateway-Get:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 'Kong'
        url:
          type: string
          example: 'http://kong.abc.com/proxy'
        subdomain_id:
          type: integer
          format: int64
          example: 10
        createdby:
          type: string
          example: 'partha'
        modifiedby:
          type: string
          example: 'partha'
        createdat:
          type: string
          format: date-time
          example: '2022-12-06T15:47:56.010Z'
        modifiedat:
          type: string
          format: date-time
          example: '2022-12-06T15:47:56.010Z'